-- MySQL Script generated by MySQL Workbench
-- Wed May 10 20:46:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tesla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tesla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tesla` DEFAULT CHARACTER SET utf8 ;
USE `tesla` ;

-- -----------------------------------------------------
-- Table `tesla`.`veiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesla`.`veiculos` (
  `id` INT NOT NULL,
  `marca` TEXT NULL,
  `modelo` TEXT NULL,
  `ano` DATE NULL,
  `cor` TEXT NULL,
  `tipo_veiculo` TEXT NULL,
  `tipo_motor` TEXT NULL,
  `combustivel` TEXT NULL,
  `cambio` TEXT NULL,
  `chassi` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
